
//
// This code was generated by a tool
// Edit AssemblyInfo.tt to actually make changes
//

using System.Reflection;
using System.Runtime.CompilerServices;

// Information about this assembly is defined by the following attributes. 
// Change them to the values specific to your project.

[assembly: AssemblyTitle("ChickenSoup")]
[assembly: AssemblyDescription("Blog/article hosting software")]
[assembly: AssemblyConfiguration(
	#if DEBUG
	"DEBUG"
	#else
	"RELEASE"
	#endif
)]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("")]
[assembly: AssemblyCopyright("David Hoppenbrouwers")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// The assembly version has the format "{Major}.{Minor}.{Build}.{Revision}".
// The form "{Major}.{Minor}.*" will automatically update the build and revision,
// and "{Major}.{Minor}.{Build}.*" will update just the revision.


[assembly: AssemblyVersion("0.9.0.*")]

// The following attributes are used to specify the signing key for the assembly, 
// if desired. See the Mono documentation for more information about signing.

//[assembly: AssemblyDelaySign(false)]
//[assembly: AssemblyKeyFile("")]


